"""Renderer for the historical mathematical Cornell page geometry."""

from __future__ import annotations

import re
import shutil
from collections.abc import Mapping
from dataclasses import dataclass
from dataclasses import field
from pathlib import Path
from textwrap import dedent
from typing import Any

from editor.cornell.identity import cornell_attribution_latex
from editor.cornell.identity import cornell_watermark_latex
from editor.cornell.latex_compat import cornell_standalone_preamble
from editor.cornell.layout import REGION_GEOMETRY
from editor.cornell.layout import REGION_LABELS
from editor.cornell.layout import CornellFitReport
from editor.cornell.layout import CornellLayoutError
from editor.cornell.layout import PageFitReport
from editor.cornell.layout import cornell_region_box_latex
from editor.cornell.layout import default_cornell_fit_report
from editor.cornell.layout import escape_latex_text
from editor.cornell.layout import measure_cornell_document_fit
from editor.cornell.media import latex_uses_svg_paths
from editor.cornell.media import prepare_cornell_image_assets
from editor.cornell.media import render_cornell_region_latex
from editor.cornell.models import CornellDocument
from editor.cornell.models import CornellPage
from editor.cornell.models import is_hybrid_compact_template
from exporters_latex.latex_compile import run_latex_until_stable
from mathkb_config import PROJECT_ROOT

HISTORICAL_LINES_IMAGE = PROJECT_ROOT / "templates_latex" / "lineas.png"
ASSETS_DIRNAME = "cornell_assets"
LINES_IMAGE_FILENAME = "lineas.png"
LINES_IMAGE_INCLUDE_PATH = f"{ASSETS_DIRNAME}/{LINES_IMAGE_FILENAME}"
SOURCE_MARKER_PATTERN = re.compile(r"% Cornell source page=(?P<page>\d+) region=(?P<region>\w+)")
LATEX_FILE_LINE_PATTERN = re.compile(r"(?P<file>[^\s:]+\.tex):(?P<line>\d+):")
LATEX_ERROR_PATTERN = re.compile(r"LaTeX Error:\s*(?P<message>.+)")
HYBRID_REGION_CONTENT_WIDTHS = {
    "cue": "2.08in",
    "main": "5.68in",
    "summary": "7.94in",
}


@dataclass(frozen=True, slots=True)
class CornellRenderResult:
    """Result object returned by the Cornell PDF renderer."""

    success: bool
    status: str
    tex_path: Path
    pdf_path: Path
    log_path: Path
    message: str = ""
    diagnostics: dict[str, Any] = field(default_factory=dict)


def _slugify_page_id(page_id: str) -> str:
    slug = re.sub(r"[^A-Za-z0-9_.-]+", "_", page_id.strip())
    return slug.strip("._") or "page"


def _slugify_output_name(output_name: str) -> str:
    return _slugify_page_id(Path(output_name).stem or output_name)


def _escape_latex_text(value: str) -> str:
    replacements = {
        "\\": r"\textbackslash{}",
        "&": r"\&",
        "%": r"\%",
        "$": r"\$",
        "#": r"\#",
        "_": r"\_",
        "{": r"\{",
        "}": r"\}",
        "~": r"\textasciitilde{}",
        "^": r"\textasciicircum{}",
    }
    return "".join(replacements.get(character, character) for character in value)


def _latex_preamble(*, include_svg: bool = False) -> str:
    return cornell_standalone_preamble(
        paper_width="8.5in",
        paper_height="11in",
        include_svg=include_svg,
        document_options="12pt,letterpaper",
        header_comment="% Generated by MathMongo Cornell MVP renderer.",
    )


def _scaled_region_latex(
    region_box: str,
    scale: float,
    *,
    content_width: str | None = None,
) -> str:
    """Scale a region while retaining paragraph layout when a width is supplied."""
    if scale >= 1.0:
        return region_box
    scalable_content = region_box
    if content_width is not None:
        scalable_content = dedent(
            rf"""
            \begin{{minipage}}[t]{{{content_width}}}
            {region_box}
            \end{{minipage}}
            """
        ).strip()
    return dedent(
        rf"""
        \begin{{adjustbox}}{{scale={scale:.6f}}}
        {scalable_content}
        \end{{adjustbox}}
        """
    ).strip()


def _region_scope_latex(
    page: CornellPage,
    region_name: str,
    *,
    page_number: int,
    fit_report: CornellFitReport,
    asset_paths_by_id: Mapping[str, str] | None = None,
) -> str:
    geometry = REGION_GEOMETRY[region_name]
    scale = fit_report.region_scale(page_number, region_name)
    region_box = cornell_region_box_latex(
        page,
        region_name,
        page_number=page_number,
        asset_paths_by_id=asset_paths_by_id,
    )
    region_content = _scaled_region_latex(region_box, scale)
    return dedent(
        rf"""
        \begin{{scope}}
          \clip {geometry.clip_top_left} rectangle {geometry.clip_bottom_right};
          \node[anchor=north west, inner sep=0pt] at {geometry.anchor} {{
            {region_content}
          }};
        \end{{scope}}
        """
    ).strip()


def _cornell_hybrid_sheet_style_latex() -> str:
    """Return the semantic colours and typography for the continuous hybrid sheet."""
    return dedent(
        r"""
        % Continuous hybrid Cornell palette, derived from the documented semantic colors.
        \definecolor{CornellHybridCue}{HTML}{2E7D32}
        \definecolor{CornellHybridMain}{HTML}{C2185B}
        \definecolor{CornellHybridSummary}{HTML}{1565C0}
        \definecolor{CornellHybridCueSoft}{HTML}{EAF5EA}
        \definecolor{CornellHybridMainSoft}{HTML}{FCEAF3}
        \definecolor{CornellHybridSummarySoft}{HTML}{EAF4FA}
        \definecolor{CornellHybridInk}{HTML}{1F2937}
        \newcommand{\CornellHybridCueHeading}[1]{%
          {\centering\fontsize{15}{17}\selectfont\color{CornellHybridCue}\bfseries #1\par}%
          \vspace{2mm}%
        }
        \newcommand{\CornellHybridMainHeading}[1]{%
          {\fontsize{18}{20}\selectfont\color{CornellHybridMain}\bfseries #1\par}%
          \vspace{1.5mm}%
        }
        \newcommand{\CornellHybridSummaryHeading}[1]{%
          {\fontsize{12}{14}\selectfont\color{CornellHybridSummary}\bfseries #1\par}%
          \vspace{.7mm}%
        }
        \newcommand{\CornellHybridCueBody}{%
          \normalfont\color{CornellHybridInk}\fontsize{8.2}{10.1}\selectfont\raggedright%
        }
        \newcommand{\CornellHybridMainBody}{%
          \normalfont\color{CornellHybridInk}\fontsize{9.2}{11.2}\selectfont\raggedright%
        }
        \newcommand{\CornellHybridSummaryBody}{%
          \normalfont\color{CornellHybridInk}\fontsize{8.8}{10.7}\selectfont\raggedright%
        }
        """
    ).strip()


def _hybrid_region_body_latex(
    page: CornellPage,
    region_name: str,
    *,
    page_number: int,
    fit_report: CornellFitReport,
    asset_paths_by_id: Mapping[str, str] | None = None,
) -> str:
    """Render one region with the established content and image compatibility layer."""
    region = getattr(page, region_name)
    body = render_cornell_region_latex(
        region,
        region_name=region_name,
        asset_paths_by_id=asset_paths_by_id,
    )
    scale = fit_report.region_scale(page_number, region_name)
    marker = f"% Cornell source page={page_number} region={region_name}"
    return _scaled_region_latex(
        f"{marker}\n{body}",
        scale,
        content_width=HYBRID_REGION_CONTENT_WIDTHS[region_name],
    )


def _cornell_hybrid_sheet_page_body(
    document: CornellDocument,
    page: CornellPage,
    *,
    page_number: int,
    fit_report: CornellFitReport,
    asset_paths_by_id: Mapping[str, str] | None = None,
) -> str:
    """Render one continuous Cornell sheet with fixed semantic regions."""
    cue_heading = escape_latex_text(page.cue.heading or "Preguntas clave")
    main_heading = escape_latex_text(page.main.heading or "Contenido principal")
    summary_heading = escape_latex_text(page.summary.heading or "Síntesis")
    cue_body = _hybrid_region_body_latex(
        page,
        "cue",
        page_number=page_number,
        fit_report=fit_report,
        asset_paths_by_id=asset_paths_by_id,
    )
    main_body = _hybrid_region_body_latex(
        page,
        "main",
        page_number=page_number,
        fit_report=fit_report,
        asset_paths_by_id=asset_paths_by_id,
    )
    summary_body = _hybrid_region_body_latex(
        page,
        "summary",
        page_number=page_number,
        fit_report=fit_report,
        asset_paths_by_id=asset_paths_by_id,
    )
    return dedent(
        rf"""
        \null
        \begin{{tikzpicture}}[remember picture,overlay]
          \coordinate (SW) at (current page.south west);
          \coordinate (SE) at (current page.south east);
          \coordinate (NW) at (current page.north west);
          \coordinate (NE) at (current page.north east);

          \fill[CornellHybridCueSoft,opacity=.55] (NW) rectangle ($(SW)+(2.4in,2in)$);
          \fill[CornellHybridMainSoft,opacity=.30] ($(NW)+(2.4in,0)$) rectangle ($(SE)+(0,2in)$);
          \fill[CornellHybridSummarySoft,opacity=.65] (SW) rectangle ($(SE)+(0,2in)$);

          {cornell_watermark_latex(
              document,
              asset_paths_by_id=asset_paths_by_id,
              page_number=page_number,
          )}

          \foreach \y in {{2.35,2.70,...,10.55}}{{
            \draw[black!8,line width=.25pt] ($(SW)+(2.4in,\y in)$) -- ($(SE)+(0,\y in)$);
          }}
          \draw[line width=.65pt] ($(SW)+(0,2in)$) -- ($(SE)+(0,2in)$);
          \draw[line width=.65pt] ($(SW)+(2.4in,2in)$) -- ($(NW)+(2.4in,0)$);

          \begin{{scope}}
            \clip (NW) rectangle ($(SW)+(2.4in,2in)$);
            \node[anchor=north west,inner sep=0pt] at ($(NW)+(.16in,-.18in)$) {{%
              \begin{{minipage}}[t]{{{HYBRID_REGION_CONTENT_WIDTHS["cue"]}}}
                \CornellHybridCueHeading{{{cue_heading}}}
                {{\CornellHybridCueBody
                {cue_body}
                }}
              \end{{minipage}}%
            }};
          \end{{scope}}

          \begin{{scope}}
            \clip ($(NW)+(2.4in,0)$) rectangle ($(SE)+(0,2in)$);
            \node[anchor=north west,inner sep=0pt] at ($(NW)+(2.58in,-.14in)$) {{%
              \begin{{minipage}}[t]{{{HYBRID_REGION_CONTENT_WIDTHS["main"]}}}
                \CornellHybridMainHeading{{{main_heading}}}
                {{\CornellHybridMainBody
                {main_body}
                }}
              \end{{minipage}}%
            }};
          \end{{scope}}

          \begin{{scope}}
            \clip (SW) rectangle ($(SE)+(0,2in)$);
            \node[anchor=north west,inner sep=0pt] at ($(SW)+(.28in,1.78in)$) {{%
              \begin{{minipage}}[t]{{{HYBRID_REGION_CONTENT_WIDTHS["summary"]}}}
                \CornellHybridSummaryHeading{{{summary_heading}}}
                {{\CornellHybridSummaryBody
                {summary_body}
                }}
              \end{{minipage}}%
            }};
          \end{{scope}}

          {cornell_attribution_latex(document)}
        \end{{tikzpicture}}
        """
    ).strip() + "\n"


def _cornell_page_body(
    document: CornellDocument,
    page: CornellPage,
    *,
    page_number: int,
    fit_report: CornellFitReport,
    asset_paths_by_id: Mapping[str, str] | None = None,
    lines_image_path: str | None = LINES_IMAGE_INCLUDE_PATH,
) -> str:
    background_block = ""
    if lines_image_path:
        background_block = rf"""
        \begin{{scope}}
          \clip ($(SW)+(2.5in,2in)$) rectangle (NE);
          \node[anchor=north west, inner sep=0pt, opacity=.2] at ($(NW)+(2.5in,-1.11in)$)
            {{\includegraphics[width=6in]{{{lines_image_path}}}}};
        \end{{scope}}
        """

    return dedent(
        rf"""
        \null
        \begin{{tikzpicture}}[remember picture,overlay]
          \coordinate (SW) at (current page.south west);
          \coordinate (SE) at (current page.south east);
          \coordinate (NW) at (current page.north west);
          \coordinate (NE) at (current page.north east);

          {cornell_watermark_latex(
              document,
              asset_paths_by_id=asset_paths_by_id,
              page_number=page_number,
          )}

        {dedent(background_block).strip()}

          \draw[line width=.4pt] ($(SW)+(0,2in)$) -- ($(SE)+(0,2in)$);
          \draw[line width=.4pt] ($(SW)+(2.4in,2in)$) -- ($(NW)+(2.4in,0)$);

          {_region_scope_latex(page, "cue", page_number=page_number, fit_report=fit_report, asset_paths_by_id=asset_paths_by_id)}

          {_region_scope_latex(page, "main", page_number=page_number, fit_report=fit_report, asset_paths_by_id=asset_paths_by_id)}

          {_region_scope_latex(page, "summary", page_number=page_number, fit_report=fit_report, asset_paths_by_id=asset_paths_by_id)}

          {cornell_attribution_latex(document)}
        \end{{tikzpicture}}
        """
    ).strip() + "\n"


def _generate_document_tex(
    document: CornellDocument,
    *,
    fit_report: CornellFitReport | None = None,
    asset_paths_by_id: Mapping[str, str] | None = None,
    lines_image_path: str | None = LINES_IMAGE_INCLUDE_PATH,
) -> str:
    pages = document.ordered_pages()
    if not pages:
        raise ValueError("CornellDocument must contain at least one page")
    if fit_report is None:
        fit_report = default_cornell_fit_report(document)
    hybrid_sheet = is_hybrid_compact_template(document.template_id)
    page_bodies = [
        (
            _cornell_hybrid_sheet_page_body(
                document,
                page,
                page_number=index,
                fit_report=fit_report,
                asset_paths_by_id=asset_paths_by_id,
            )
            if hybrid_sheet
            else _cornell_page_body(
                document,
                page,
                page_number=index,
                fit_report=fit_report,
                asset_paths_by_id=asset_paths_by_id,
                lines_image_path=lines_image_path,
            )
        ).strip()
        for index, page in enumerate(pages, start=1)
    ]
    return (
        _latex_preamble(include_svg=latex_uses_svg_paths(dict(asset_paths_by_id or {})))
        + ("\n" + _cornell_hybrid_sheet_style_latex() if hybrid_sheet else "")
        + "\n\n\\begin{document}\n"
        + "\n\\clearpage\n".join(page_bodies)
        + "\n\\end{document}\n"
    )


def generate_cornell_tex(
    page: CornellPage,
    *,
    fit_report: CornellFitReport | None = None,
    asset_paths_by_id: Mapping[str, str] | None = None,
    lines_image_path: str | None = LINES_IMAGE_INCLUDE_PATH,
) -> str:
    """Generate the one-page LaTeX source for a Cornell page."""
    document = CornellDocument(schema_version=1, template_id="source_generation", pages=(page,))
    return _generate_document_tex(
        document,
        fit_report=fit_report,
        asset_paths_by_id=asset_paths_by_id,
        lines_image_path=lines_image_path,
    )


def generate_cornell_document_tex(
    document: CornellDocument,
    *,
    fit_report: CornellFitReport | None = None,
    asset_paths_by_id: Mapping[str, str] | None = None,
    lines_image_path: str | None = LINES_IMAGE_INCLUDE_PATH,
) -> str:
    """Generate a single LaTeX document for all Cornell pages in order."""
    return _generate_document_tex(
        document,
        fit_report=fit_report,
        asset_paths_by_id=asset_paths_by_id,
        lines_image_path=lines_image_path,
    )


def _prepare_output_dir(
    output_dir: str | Path,
    document: CornellDocument | None = None,
    *,
    db: Any | None = None,
    assets_by_id: Mapping[str, Mapping[str, Any]] | None = None,
    warnings: list[str] | None = None,
) -> tuple[Path, dict[str, str]]:
    output_path = Path(output_dir)
    output_path.mkdir(parents=True, exist_ok=True)
    assets_path = output_path / ASSETS_DIRNAME
    assets_path.mkdir(parents=True, exist_ok=True)
    shutil.copyfile(HISTORICAL_LINES_IMAGE, assets_path / LINES_IMAGE_FILENAME)
    shutil.copyfile(
        PROJECT_ROOT / "templates_latex" / "mathmongo-macros.sty",
        output_path / "mathmongo-macros.sty",
    )
    image_paths = {}
    if document is not None:
        image_paths = prepare_cornell_image_assets(
            document,
            output_path,
            db=db,
            assets_by_id=assets_by_id,
            warnings=warnings,
        )
    return output_path, image_paths


def write_cornell_tex(
    page: CornellPage,
    output_dir: str | Path,
    *,
    fit_report: CornellFitReport | None = None,
    db: Any | None = None,
    assets_by_id: Mapping[str, Mapping[str, Any]] | None = None,
) -> Path:
    """Write a Cornell page source file and its renderer asset."""
    document = CornellDocument(schema_version=1, template_id="single_page_render", pages=(page,))
    output_path, image_paths = _prepare_output_dir(
        output_dir,
        document,
        db=db,
        assets_by_id=assets_by_id,
    )

    tex_path = output_path / f"cornell_{_slugify_page_id(page.page_id)}.tex"
    tex_path.write_text(
        generate_cornell_tex(page, fit_report=fit_report, asset_paths_by_id=image_paths),
        encoding="utf-8",
    )
    return tex_path


def _write_cornell_document_tex_with_assets(
    document: CornellDocument,
    output_path: Path,
    output_name: str,
    *,
    asset_paths_by_id: Mapping[str, str],
    fit_report: CornellFitReport | None = None,
) -> Path:
    tex_path = output_path / f"{_slugify_output_name(output_name)}.tex"
    tex_path.write_text(
        generate_cornell_document_tex(
            document,
            fit_report=fit_report,
            asset_paths_by_id=asset_paths_by_id,
        ),
        encoding="utf-8",
    )
    return tex_path


def write_cornell_document_tex(
    document: CornellDocument,
    output_dir: str | Path,
    output_name: str,
    *,
    fit_report: CornellFitReport | None = None,
    db: Any | None = None,
    assets_by_id: Mapping[str, Mapping[str, Any]] | None = None,
) -> Path:
    """Write a complete Cornell document source file and its renderer asset."""
    output_path, image_paths = _prepare_output_dir(
        output_dir,
        document,
        db=db,
        assets_by_id=assets_by_id,
    )
    return _write_cornell_document_tex_with_assets(
        document,
        output_path,
        output_name,
        asset_paths_by_id=image_paths,
        fit_report=fit_report,
    )


def _compile_cornell_tex(tex_path: Path, output_path: Path) -> CornellRenderResult:
    pdf_path = tex_path.with_suffix(".pdf")
    log_path = tex_path.with_suffix(".log")
    command = [
        "pdflatex",
        "-interaction=nonstopmode",
        "-halt-on-error",
        "-file-line-error",
        tex_path.name,
    ]
    diagnostics = run_latex_until_stable(
        command,
        cwd=output_path,
        tex_file=tex_path.name,
        pdf_path=pdf_path,
        log_path=log_path,
    )
    status = str(diagnostics.get("status") or "failed")
    success = status in {"success", "success_with_warnings"}
    if success:
        message = "PDF generated successfully."
    else:
        message = summarize_cornell_latex_failure(tex_path, diagnostics)
    return CornellRenderResult(
        success=success,
        status=status,
        tex_path=tex_path,
        pdf_path=pdf_path,
        log_path=log_path,
        message=message,
        diagnostics=diagnostics,
    )


def _line_number_from_diagnostics(diagnostics: Mapping[str, Any]) -> int | None:
    text = "\n".join(
        str(diagnostics.get(key) or "")
        for key in ("log_excerpt", "stderr", "stdout", "log_text")
    )
    file_line_match = LATEX_FILE_LINE_PATTERN.search(text)
    if file_line_match:
        return int(file_line_match.group("line"))
    line_match = re.search(r"\bl\.(?P<line>\d+)\b", text)
    if line_match:
        return int(line_match.group("line"))
    return None


def _latex_error_from_diagnostics(diagnostics: Mapping[str, Any]) -> str:
    text = "\n".join(
        str(diagnostics.get(key) or "")
        for key in ("log_excerpt", "stderr", "stdout", "log_text")
    )
    latex_match = LATEX_ERROR_PATTERN.search(text)
    if latex_match:
        return latex_match.group("message").strip()
    for line in text.splitlines():
        clean = line.strip()
        if clean.startswith("!") and len(clean) > 1:
            return clean.lstrip("!").strip()
    return "PDF generation failed."


def _source_region_for_line(tex_path: Path, line_number: int | None) -> tuple[int, str] | None:
    if line_number is None or not tex_path.exists():
        return None
    source = tex_path.read_text(encoding="utf-8", errors="replace").splitlines()
    markers: list[tuple[int, int, str]] = []
    for index, line in enumerate(source, start=1):
        marker = SOURCE_MARKER_PATTERN.search(line)
        if marker:
            markers.append((index, int(marker.group("page")), marker.group("region")))
    selected = None
    for marker_line, page_number, region in markers:
        if marker_line <= line_number:
            selected = (page_number, region)
        else:
            break
    return selected


def summarize_cornell_latex_failure(tex_path: Path, diagnostics: Mapping[str, Any]) -> str:
    """Build a short, UI-friendly LaTeX failure summary for Cornell PDFs."""
    error = _latex_error_from_diagnostics(diagnostics)
    region = _source_region_for_line(tex_path, _line_number_from_diagnostics(diagnostics))
    if region is None:
        return error
    page_number, region_name = region
    region_label = REGION_LABELS.get(region_name, region_name)
    return f"Error LaTeX en pagina {page_number}, region {region_label}: {error}"


def cornell_latex_full_log(result: CornellRenderResult) -> str:
    """Return the complete LaTeX log when available, falling back to diagnostics/message."""
    for key in ("log_text", "log_excerpt", "stderr", "stdout"):
        value = result.diagnostics.get(key)
        if value:
            return str(value)
    return result.message


def _fit_overflow_message(fit_report: CornellFitReport) -> str:
    overflow_regions = fit_report.overflow_regions()
    if not overflow_regions:
        return "El ajuste Cornell no pudo completarse."
    page_report, region = overflow_regions[0]
    lines = [
        f"Página {page_report.page_id} · {region.label}",
        f"Escala necesaria: {region.required_scale:.2f}",
        f"Escala mínima: {fit_report.min_region_scale:.2f}",
    ]
    if len(overflow_regions) > 1:
        lines.append(f"Regiones con overflow: {len(overflow_regions)}")
    return "\n".join(lines)


def _fit_overflow_diagnostics(fit_report: CornellFitReport) -> dict[str, Any]:
    return {
        "fit_report": fit_report.to_dict(),
        "overflow_regions": [
            {
                "page_id": page.page_id,
                "page_number": page.page_number,
                "region": region.region,
                "label": region.label,
                "required_scale": region.required_scale,
                "min_region_scale": fit_report.min_region_scale,
            }
            for page, region in fit_report.overflow_regions()
        ],
    }


def _remove_stale_pdf(pdf_path: Path) -> None:
    try:
        if pdf_path.exists():
            pdf_path.unlink()
    except OSError:
        pass


def _preflight_cornell_fit(
    document: CornellDocument,
    output_path: Path,
    output_name: str,
    *,
    asset_paths_by_id: Mapping[str, str],
) -> CornellFitReport:
    return measure_cornell_document_fit(
        document,
        output_path,
        output_name,
        latex_preamble=_latex_preamble(include_svg=latex_uses_svg_paths(dict(asset_paths_by_id))),
        asset_paths_by_id=asset_paths_by_id,
    )


def measure_cornell_page_fit(
    page: CornellPage,
    output_dir: str | Path,
    output_name: str,
    *,
    db: Any | None = None,
    assets_by_id: Mapping[str, Mapping[str, Any]] | None = None,
) -> PageFitReport:
    """Measure all regions in one Cornell page using the renderer preflight."""
    document = CornellDocument(schema_version=1, template_id="single_page_fit", pages=(page,))
    output_path, image_paths = _prepare_output_dir(
        output_dir,
        document,
        db=db,
        assets_by_id=assets_by_id,
    )
    fit_report = _preflight_cornell_fit(
        document,
        output_path,
        output_name,
        asset_paths_by_id=image_paths,
    )
    return fit_report.pages[0]


def render_cornell_pdf(
    page: CornellPage,
    output_dir: str | Path,
    *,
    db: Any | None = None,
    assets_by_id: Mapping[str, Mapping[str, Any]] | None = None,
) -> CornellRenderResult:
    """Render a single Cornell page directly to a PDF."""
    output_path = Path(output_dir)
    tex_path = output_path / f"cornell_{_slugify_page_id(page.page_id)}.tex"
    pdf_path = tex_path.with_suffix(".pdf")
    log_path = tex_path.with_suffix(".log")

    try:
        document = CornellDocument(schema_version=1, template_id="single_page_render", pages=(page,))
        output_path, image_paths = _prepare_output_dir(
            output_path,
            document,
            db=db,
            assets_by_id=assets_by_id,
        )
        fit_report = _preflight_cornell_fit(
            document,
            output_path,
            tex_path.stem,
            asset_paths_by_id=image_paths,
        )
        if fit_report.has_overflow:
            _remove_stale_pdf(pdf_path)
            return CornellRenderResult(
                success=False,
                status="overflow",
                tex_path=tex_path,
                pdf_path=pdf_path,
                log_path=log_path,
                message=_fit_overflow_message(fit_report),
                diagnostics=_fit_overflow_diagnostics(fit_report),
            )
        tex_path = _write_cornell_document_tex_with_assets(
            document,
            output_path,
            tex_path.stem,
            asset_paths_by_id=image_paths,
            fit_report=fit_report,
        )
        result = _compile_cornell_tex(tex_path, output_path)
        result.diagnostics["fit_report"] = fit_report.to_dict()
        return result
    except CornellLayoutError as exc:
        return CornellRenderResult(
            success=False,
            status="failed",
            tex_path=tex_path,
            pdf_path=pdf_path,
            log_path=log_path,
            message=str(exc),
            diagnostics=exc.diagnostics,
        )
    except Exception as exc:
        return CornellRenderResult(
            success=False,
            status="failed",
            tex_path=tex_path,
            pdf_path=pdf_path,
            log_path=log_path,
            message=str(exc),
            diagnostics={"exception_type": type(exc).__name__},
        )


def render_cornell_document(
    document: CornellDocument,
    output_dir: str | Path,
    output_name: str,
    *,
    db: Any | None = None,
    assets_by_id: Mapping[str, Mapping[str, Any]] | None = None,
) -> CornellRenderResult:
    """Render all Cornell pages into one LaTeX document and one PDF."""
    output_path = Path(output_dir)
    tex_path = output_path / f"{_slugify_output_name(output_name)}.tex"
    pdf_path = tex_path.with_suffix(".pdf")
    log_path = tex_path.with_suffix(".log")
    warnings: list[str] = []

    try:
        output_path, image_paths = _prepare_output_dir(
            output_path,
            document,
            db=db,
            assets_by_id=assets_by_id,
            warnings=warnings,
        )
        fit_report = _preflight_cornell_fit(
            document,
            output_path,
            output_name,
            asset_paths_by_id=image_paths,
        )
        if fit_report.has_overflow:
            _remove_stale_pdf(pdf_path)
            return CornellRenderResult(
                success=False,
                status="overflow",
                tex_path=tex_path,
                pdf_path=pdf_path,
                log_path=log_path,
                message=_fit_overflow_message(fit_report),
                diagnostics={
                    **_fit_overflow_diagnostics(fit_report),
                    "warnings": warnings,
                },
            )
        tex_path = _write_cornell_document_tex_with_assets(
            document,
            output_path,
            output_name,
            asset_paths_by_id=image_paths,
            fit_report=fit_report,
        )
        result = _compile_cornell_tex(tex_path, output_path)
        result.diagnostics["fit_report"] = fit_report.to_dict()
        result.diagnostics["warnings"] = warnings
        return result
    except CornellLayoutError as exc:
        return CornellRenderResult(
            success=False,
            status="failed",
            tex_path=tex_path,
            pdf_path=pdf_path,
            log_path=log_path,
            message=str(exc),
            diagnostics={**exc.diagnostics, "warnings": warnings},
        )
    except Exception as exc:
        return CornellRenderResult(
            success=False,
            status="failed",
            tex_path=tex_path,
            pdf_path=pdf_path,
            log_path=log_path,
            message=str(exc),
            diagnostics={"exception_type": type(exc).__name__, "warnings": warnings},
        )
