"""Renderer for the historical mathematical Cornell page geometry."""

from __future__ import annotations

import re
import shutil
from dataclasses import dataclass
from dataclasses import field
from pathlib import Path
from textwrap import dedent
from typing import Any

from editor.cornell.models import CornellDocument
from editor.cornell.models import CornellPage
from exporters_latex.latex_compile import run_latex_until_stable
from mathkb_config import PROJECT_ROOT

HISTORICAL_CORNELL_DIR = PROJECT_ROOT / "CornellFormats" / "1 Notas matemáticas tipo cornel"
HISTORICAL_LINES_IMAGE = HISTORICAL_CORNELL_DIR / "lineas.png"
ASSETS_DIRNAME = "cornell_assets"
LINES_IMAGE_FILENAME = "lineas.png"
LINES_IMAGE_INCLUDE_PATH = f"{ASSETS_DIRNAME}/{LINES_IMAGE_FILENAME}"


@dataclass(frozen=True, slots=True)
class CornellRenderResult:
    """Result object returned by the Cornell PDF renderer."""

    success: bool
    status: str
    tex_path: Path
    pdf_path: Path
    log_path: Path
    message: str = ""
    diagnostics: dict[str, Any] = field(default_factory=dict)


def _slugify_page_id(page_id: str) -> str:
    slug = re.sub(r"[^A-Za-z0-9_.-]+", "_", page_id.strip())
    return slug.strip("._") or "page"


def _slugify_output_name(output_name: str) -> str:
    return _slugify_page_id(Path(output_name).stem or output_name)


def _escape_latex_text(value: str) -> str:
    replacements = {
        "\\": r"\textbackslash{}",
        "&": r"\&",
        "%": r"\%",
        "$": r"\$",
        "#": r"\#",
        "_": r"\_",
        "{": r"\{",
        "}": r"\}",
        "~": r"\textasciitilde{}",
        "^": r"\textasciicircum{}",
    }
    return "".join(replacements.get(character, character) for character in value)


def _latex_preamble() -> str:
    return dedent(
        r"""
        % Generated by MathMongo Cornell MVP renderer.
        \documentclass[12pt,letterpaper]{article}
        \usepackage[utf8]{inputenc}
        \usepackage[T1]{fontenc}
        \usepackage[paperwidth=8.5in,paperheight=11in,margin=0in]{geometry}
        \usepackage{amsmath,amssymb,amsfonts}
        \usepackage{graphicx}
        \usepackage[dvipsnames,svgnames]{xcolor}
        \usepackage{tikz}
        \usetikzlibrary{calc}
        \pagestyle{empty}
        \setlength{\parindent}{0pt}
        \setlength{\parskip}{4pt}
        \newcommand{\CornellMainText}{\normalfont\color{black}\fontsize{10}{18.9}\selectfont}
        \newcommand{\CornellCueHeading}[1]{\begin{center}{\Huge\color{OliveGreen} #1}\end{center}}
        \newcommand{\CornellMainHeading}[1]{%
          \begin{minipage}{1mm}\rule{0pt}{2.1cm}\end{minipage}%
          \begin{minipage}{5.45in}{\Huge\color{RubineRed} #1}\end{minipage}\par%
        }
        \newcommand{\CornellSummaryHeading}[1]{{\color{blue}\bfseries\large #1}\par}
        """
    ).strip()


def _cornell_page_body(
    page: CornellPage,
    *,
    lines_image_path: str | None = LINES_IMAGE_INCLUDE_PATH,
) -> str:
    cue_heading = _escape_latex_text(page.cue.heading)
    main_heading = _escape_latex_text(page.main.heading)
    summary_heading = _escape_latex_text(page.summary.heading)
    background_block = ""
    if lines_image_path:
        background_block = rf"""
        \begin{{scope}}
          \clip ($(SW)+(2.5in,2in)$) rectangle (NE);
          \node[anchor=north west, inner sep=0pt, opacity=.2] at ($(NW)+(2.5in,-1.11in)$)
            {{\includegraphics[width=6in]{{{lines_image_path}}}}};
        \end{{scope}}
        """

    return dedent(
        rf"""
        \null
        \begin{{tikzpicture}}[remember picture,overlay]
          \coordinate (SW) at (current page.south west);
          \coordinate (SE) at (current page.south east);
          \coordinate (NW) at (current page.north west);
          \coordinate (NE) at (current page.north east);

        {dedent(background_block).strip()}

          \draw[line width=.4pt] ($(SW)+(0,2in)$) -- ($(SE)+(0,2in)$);
          \draw[line width=.4pt] ($(SW)+(2.4in,2in)$) -- ($(NW)+(2.4in,0)$);

          \node[anchor=north west, inner sep=0pt] at (NW) {{
            \begin{{minipage}}[t][9in][t]{{2.3in}}
              \vspace{{5mm}}
              \hspace*{{4mm}}\begin{{minipage}}[t]{{2.05in}}
                {{\setlength{{\fboxrule}}{{1pt}}\setlength{{\fboxsep}}{{3pt}}%
                \fcolorbox{{gray}}{{white}}{{%
                  \begin{{minipage}}{{1.93in}}
                    \CornellCueHeading{{{cue_heading}}}
                  \end{{minipage}}%
                }}}}
                \par\vspace{{4mm}}
                \CornellMainText
                {page.cue.latex}
              \end{{minipage}}
            \end{{minipage}}
          }};

          \node[anchor=north west, inner sep=0pt] at ($(NW)+(2.5in,0)$) {{
            \begin{{minipage}}[t][9in][t]{{6in}}
              \vspace{{.2cm}}
              \hspace*{{4mm}}\begin{{minipage}}[t]{{5.52in}}
                \CornellMainHeading{{{main_heading}}}
                \CornellMainText
                {page.main.latex}
              \end{{minipage}}
            \end{{minipage}}
          }};

          \node[anchor=north west, inner sep=0pt] at ($(SW)+(0,2in)$) {{
            \begin{{minipage}}[t][2in][t]{{8.5in}}
              \vspace{{4mm}}
              \hspace*{{18mm}}\begin{{minipage}}[t]{{7.43in}}
                \CornellSummaryHeading{{{summary_heading}}}
                \CornellMainText
                {page.summary.latex}
              \end{{minipage}}
            \end{{minipage}}
          }};
        \end{{tikzpicture}}
        """
    ).strip() + "\n"


def _generate_document_tex(
    pages: tuple[CornellPage, ...],
    *,
    lines_image_path: str | None = LINES_IMAGE_INCLUDE_PATH,
) -> str:
    if not pages:
        raise ValueError("CornellDocument must contain at least one page")
    page_bodies = [
        _cornell_page_body(page, lines_image_path=lines_image_path).strip() for page in pages
    ]
    return (
        _latex_preamble()
        + "\n\n\\begin{document}\n"
        + "\n\\clearpage\n".join(page_bodies)
        + "\n\\end{document}\n"
    )


def generate_cornell_tex(
    page: CornellPage,
    *,
    lines_image_path: str | None = LINES_IMAGE_INCLUDE_PATH,
) -> str:
    """Generate the one-page LaTeX source for a Cornell page."""
    return _generate_document_tex((page,), lines_image_path=lines_image_path)


def generate_cornell_document_tex(
    document: CornellDocument,
    *,
    lines_image_path: str | None = LINES_IMAGE_INCLUDE_PATH,
) -> str:
    """Generate a single LaTeX document for all Cornell pages in order."""
    return _generate_document_tex(document.ordered_pages(), lines_image_path=lines_image_path)


def _prepare_output_dir(output_dir: str | Path) -> Path:
    output_path = Path(output_dir)
    output_path.mkdir(parents=True, exist_ok=True)
    assets_path = output_path / ASSETS_DIRNAME
    assets_path.mkdir(parents=True, exist_ok=True)
    shutil.copyfile(HISTORICAL_LINES_IMAGE, assets_path / LINES_IMAGE_FILENAME)
    return output_path


def write_cornell_tex(page: CornellPage, output_dir: str | Path) -> Path:
    """Write a Cornell page source file and its renderer asset."""
    output_path = _prepare_output_dir(output_dir)

    tex_path = output_path / f"cornell_{_slugify_page_id(page.page_id)}.tex"
    tex_path.write_text(generate_cornell_tex(page), encoding="utf-8")
    return tex_path


def write_cornell_document_tex(
    document: CornellDocument,
    output_dir: str | Path,
    output_name: str,
) -> Path:
    """Write a complete Cornell document source file and its renderer asset."""
    output_path = _prepare_output_dir(output_dir)
    tex_path = output_path / f"{_slugify_output_name(output_name)}.tex"
    tex_path.write_text(generate_cornell_document_tex(document), encoding="utf-8")
    return tex_path


def _compile_cornell_tex(tex_path: Path, output_path: Path) -> CornellRenderResult:
    pdf_path = tex_path.with_suffix(".pdf")
    log_path = tex_path.with_suffix(".log")
    command = [
        "pdflatex",
        "-interaction=nonstopmode",
        "-halt-on-error",
        "-file-line-error",
        tex_path.name,
    ]
    diagnostics = run_latex_until_stable(
        command,
        cwd=output_path,
        tex_file=tex_path.name,
        pdf_path=pdf_path,
        log_path=log_path,
    )
    status = str(diagnostics.get("status") or "failed")
    success = status in {"success", "success_with_warnings"}
    if success:
        message = "PDF generated successfully."
    else:
        message = diagnostics.get("log_excerpt") or diagnostics.get("stderr") or "PDF generation failed."
    return CornellRenderResult(
        success=success,
        status=status,
        tex_path=tex_path,
        pdf_path=pdf_path,
        log_path=log_path,
        message=message,
        diagnostics=diagnostics,
    )


def render_cornell_pdf(page: CornellPage, output_dir: str | Path) -> CornellRenderResult:
    """Render a single Cornell page directly to a PDF."""
    output_path = Path(output_dir)
    tex_path = output_path / f"cornell_{_slugify_page_id(page.page_id)}.tex"
    pdf_path = tex_path.with_suffix(".pdf")
    log_path = tex_path.with_suffix(".log")

    try:
        tex_path = write_cornell_tex(page, output_path)
        return _compile_cornell_tex(tex_path, output_path)
    except Exception as exc:
        return CornellRenderResult(
            success=False,
            status="failed",
            tex_path=tex_path,
            pdf_path=pdf_path,
            log_path=log_path,
            message=str(exc),
            diagnostics={"exception_type": type(exc).__name__},
        )


def render_cornell_document(
    document: CornellDocument,
    output_dir: str | Path,
    output_name: str,
) -> CornellRenderResult:
    """Render all Cornell pages into one LaTeX document and one PDF."""
    output_path = Path(output_dir)
    tex_path = output_path / f"{_slugify_output_name(output_name)}.tex"
    pdf_path = tex_path.with_suffix(".pdf")
    log_path = tex_path.with_suffix(".log")

    try:
        tex_path = write_cornell_document_tex(document, output_path, output_name)
        return _compile_cornell_tex(tex_path, output_path)
    except Exception as exc:
        return CornellRenderResult(
            success=False,
            status="failed",
            tex_path=tex_path,
            pdf_path=pdf_path,
            log_path=log_path,
            message=str(exc),
            diagnostics={"exception_type": type(exc).__name__},
        )
