"""Reusable, persistence-free Source form helpers for S1B."""

from __future__ import annotations

from collections.abc import Mapping
from dataclasses import dataclass
from typing import Any

from pydantic import ValidationError

from editor.source_catalog.shared import split_values
from editor.source_catalog.state import state_key
from mathmongo.source_catalog.models import CopyrightStatus
from mathmongo.source_catalog.models import RedistributionPolicy
from mathmongo.source_catalog.models import Source
from mathmongo.source_catalog.models import SourceType


@dataclass(frozen=True, slots=True)
class SourceFormDraft:
    """Validated unsaved Source plus safe field-level errors."""

    values: Mapping[str, Any]
    source: Source | None
    errors: tuple[str, ...] = ()

    @property
    def valid(self) -> bool:
        """Return whether the Source can proceed to duplicate preview."""
        return self.source is not None and not self.errors


def _optional_text(value: Any) -> str | None:
    text = "" if value is None else str(value).strip()
    return text or None


def _validation_messages(error: ValidationError) -> tuple[str, ...]:
    return tuple(
        f"{'.'.join(str(part) for part in item.get('loc', ())) or 'source'}: "
        f"{item.get('msg', 'invalid value')}"
        for item in error.errors(include_url=False, include_context=False, include_input=False)
    )


def build_source_from_form(
    values: Mapping[str, Any],
    *,
    initial: Source | Mapping[str, Any] | None = None,
) -> Source:
    """Build a domain Source while preserving an existing stable ID."""
    current = (
        initial
        if isinstance(initial, Source)
        else Source.model_validate(initial)
        if initial is not None
        else None
    )
    data = current.model_dump(mode="python") if current is not None else {}
    data.update(
        {
            "name": str(values.get("name") or ""),
            "description": str(values.get("description") or ""),
            "source_type": values.get("source_type", SourceType.OTHER.value),
            "language": _optional_text(values.get("language")),
            "aliases": split_values(str(values.get("aliases_text") or "")),
            "tags": split_values(str(values.get("tags_text") or "")),
            "rights_default": {
                "copyright_status": values.get("copyright_status", CopyrightStatus.UNKNOWN.value),
                "redistribution": values.get("redistribution", RedistributionPolicy.ASK.value),
                "license": _optional_text(values.get("license")),
                "notes": _optional_text(values.get("rights_notes")),
            },
        }
    )
    return Source.model_validate(data)


def _defaults(source: Source | None) -> dict[str, Any]:
    rights = source.rights_default if source is not None else None
    return {
        "name": source.name if source is not None else "",
        "description": source.description if source is not None else "",
        "source_type": source.source_type.value if source is not None else SourceType.OTHER.value,
        "language": source.language or "" if source is not None else "",
        "aliases_text": "\n".join(alias.value for alias in source.aliases) if source else "",
        "tags_text": ", ".join(source.tags) if source else "",
        "copyright_status": (
            rights.copyright_status.value if rights else CopyrightStatus.UNKNOWN.value
        ),
        "redistribution": rights.redistribution.value if rights else RedistributionPolicy.ASK.value,
        "license": rights.license or "" if rights else "",
        "rights_notes": rights.notes or "" if rights else "",
    }


def render_source_form(
    ui: Any,
    *,
    key_prefix: str,
    initial: Source | Mapping[str, Any] | None = None,
) -> SourceFormDraft:
    """Render Source fields and return a validated, non-persisted draft."""
    current: Source | None = None
    initial_errors: tuple[str, ...] = ()
    try:
        if initial is not None:
            current = initial if isinstance(initial, Source) else Source.model_validate(initial)
    except ValidationError as exc:
        initial_errors = _validation_messages(exc)
    defaults = _defaults(current)
    if current is None:
        ui.caption("Source ID: generated by the system after validation; it is not editable.")
    else:
        ui.caption(f"Source ID: {current.source_id} · stable and read-only")

    name = ui.text_input(
        "Name *",
        value=defaults["name"],
        key=state_key(key_prefix, "name"),
    )
    description = ui.text_area(
        "Display / description",
        value=defaults["description"],
        key=state_key(key_prefix, "description"),
    )
    type_values = [item.value for item in SourceType]
    source_type = ui.selectbox(
        "Source type",
        type_values,
        index=type_values.index(defaults["source_type"]),
        key=state_key(key_prefix, "source_type"),
    )
    language = ui.text_input(
        "Language",
        value=defaults["language"],
        key=state_key(key_prefix, "language"),
    )
    aliases_text = ui.text_area(
        "Aliases",
        value=defaults["aliases_text"],
        key=state_key(key_prefix, "aliases"),
        help="Separate aliases with commas or new lines.",
    )
    tags_text = ui.text_input(
        "Tags",
        value=defaults["tags_text"],
        key=state_key(key_prefix, "tags"),
        help="Separate tags with commas or new lines.",
    )
    ui.markdown("**Default rights**")
    copyright_values = [item.value for item in CopyrightStatus]
    copyright_status = ui.selectbox(
        "Copyright status",
        copyright_values,
        index=copyright_values.index(defaults["copyright_status"]),
        key=state_key(key_prefix, "copyright_status"),
    )
    redistribution_values = [item.value for item in RedistributionPolicy]
    redistribution = ui.selectbox(
        "Redistribution",
        redistribution_values,
        index=redistribution_values.index(defaults["redistribution"]),
        key=state_key(key_prefix, "redistribution"),
    )
    license_value = ui.text_input(
        "License",
        value=defaults["license"],
        key=state_key(key_prefix, "license"),
    )
    rights_notes = ui.text_area(
        "Rights notes",
        value=defaults["rights_notes"],
        key=state_key(key_prefix, "rights_notes"),
    )
    values = {
        "name": name,
        "description": description,
        "source_type": source_type,
        "language": language,
        "aliases_text": aliases_text,
        "tags_text": tags_text,
        "copyright_status": copyright_status,
        "redistribution": redistribution,
        "license": license_value,
        "rights_notes": rights_notes,
    }
    if initial_errors:
        return SourceFormDraft(values, None, initial_errors)
    try:
        source = build_source_from_form(values, initial=current)
    except ValidationError as exc:
        return SourceFormDraft(values, None, _validation_messages(exc))
    except (TypeError, ValueError) as exc:
        return SourceFormDraft(values, None, (str(exc),))
    return SourceFormDraft(values, source)


__all__ = [
    "SourceFormDraft",
    "build_source_from_form",
    "render_source_form",
]
