# .ruff.toml
line-length = 100
target-version = "py310"

[lint]
select = [
    "E",   # pycodestyle (errores)
    "F",   # pyflakes (errores de análisis estático)
    "I",   # isort (orden de imports)
    "N",   # pep8-naming
    "UP",  # pyupgrade
    "B",   # flake8-bugbear
]
ignore = [
    "E501",  # línea demasiado larga (ya lo controlamos con line-length)
]

[format]
quote-style = "double"
